language: node_js
node_js:
  - stable
services:
  - postgresql
cache:
  directories:
    - node_modules
before_install:
  - npm install
install:
  - npm install
before_script:
  - psql -c 'create database konsole_test;' -U postgres
  - psql -c 'psql konsole_test < tests/schema.sql' -U postgres
script:
  - npm test
